controller:
  service:
    type: NodePort
    nodePorts:
      http: 30080
  readinessProbe:
    httpGet:
      path: /      # بدل /healthz
      port: 30080  # بدل 10254
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
