replicaCount: 1

image:
  repository: 869483685448.dkr.ecr.eu-west-1.amazonaws.com/prod-db-check
  tag: 9e176301e73e792ff5d9f100a0191f6a3cde12e5
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  host: demo.local                   # we'll map this in /etc/hosts
  path: /
  pathType: Prefix

mongoUri: mongodb+srv://mariam:1234@cluster0.6oezh3q.mongodb.net/?appName=Cluster0
