replicaCount: 1

image:
  repository: 869483685448.dkr.ecr.eu-west-1.amazonaws.com/prod-db-check
  tag: 4331c24a80a30a4da8599bf23e452fcf0f2367b9
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  host: demo.local                   # we'll map this in /etc/hosts
  path: /
  pathType: Prefix

mongoUri: mongodb://mariam:1234@159.41.79.59:27017,159.41.64.229:27017,159.41.79.64:27017/?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority

