name: CD - Update GitOps Repo

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - nonprod
          - prod

env:
  TF_DIR: terraform
  AWS_REGION: eu-west-1

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: Mariam072/AutoDev-Cloud-Platform
          token: ${{ secrets.GH_PAT }}

      - name: Get ECR URL from Terraform
        run: |
          cd $TF_DIR
          terraform init -input=false
          terraform workspace select ${{ github.event.inputs.env }}
          ECR_URL=$(terraform output -raw ecr_repository_url)
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV

      - name: Set Image Tag
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set Mongo URI from SSM or env
        run: |
          MONGO_URI=$(aws ssm get-parameter --name "/auto-dev-demo/mongo-uri" --with-decryption --query 'Parameter.Value' --output text --region $AWS_REGION)
          echo "MONGO_URI=$MONGO_URI" >> $GITHUB_ENV

      - name: Update Helm values
        run: |
          sed -i "s|repository:.*|repository: $ECR_URL|" helm/auto-dev-demo/values.yaml
          sed -i "s|tag:.*|tag: $IMAGE_TAG|" helm/auto-dev-demo/values.yaml
          sed -i "s|mongoUri:.*|mongoUri: $MONGO_URI|" helm/auto-dev-demo/values.yaml

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/auto-dev-demo/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG and repo to $ECR_URL"
          git push
      - name: Verification
        run: |
          echo "Verify GitOps Repo updated successfully"
          git log -1 --oneline
