name: Monitoring - Deploy Datadog

on:
  workflow_dispatch:

jobs:
  deploy-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1   # غيريها حسب الريجن بتاعك

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name prod-eks --region eu-west-1

      - name: Add Datadog Helm Repo
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo update

      - name: Create Namespace
        run: |
          kubectl create namespace datadog --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Datadog Secret
        run: |
          kubectl create secret generic datadog-secret \
            --from-literal=api-key=${{ secrets.DATADOG_API_KEY }} \
            -n datadog \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Datadog Agent
        run: |
          helm upgrade --install datadog-agent datadog/datadog \
            --namespace datadog \
            --set datadog.site=us5.datadoghq.com \
            --set datadog.clusterName=prod-eks \
            --set datadog.apiKeyExistingSecret=datadog-secret \
            --set datadog.logs.enabled=true \
            --set datadog.logs.containerCollectAll=true \
            --set datadog.apm.enabled=true \
            --set datadog.kubeStateMetricsEnabled=true \
            --set clusterAgent.enabled=true
